(()=>{"use strict";
const $=id=>document.getElementById(id);const screens=["home","select","map","battle","result","victory"];
const LEVELS=[
 {name:"第一關：生字森林",cat:["生字詞"],bg:"level1.webp",boss:"boss1",reward:{coin:50,shard:10}},
 {name:"第二關：詞語河流",cat:["語詞運用"],bg:"level2.webp",boss:"boss2",reward:{coin:70,shard:15}},
 {name:"第三關：幸福記憶",cat:["課文理解","修辭句型"],bg:"level3.webp",boss:"boss3",reward:{coin:90,shard:20}},
 {name:"第四關：時間裂隙",cat:["課文理解","修辭句型","素養情境"],bg:"level4.webp",boss:"boss4",reward:{coin:120,shard:30}}
];
let state={character:"female",unlocked:0,completed:[false,false,false,false],coins:120,shards:35,totalCorrect:0};
let run={level:0,questions:[],index:0,correct:0,lives:4,hints:3,combo:0,maxCombo:0,bossHp:100,answered:false};
const bank=window.QUESTION_BANK.questions;
function show(id){screens.forEach(s=>$(s).classList.toggle("active",s===id))}
function save(){localStorage.setItem("timeRepairV1",JSON.stringify(state));$("continueGame").classList.remove("hidden")}
function load(){try{const x=JSON.parse(localStorage.getItem("timeRepairV1"));if(x)state={...state,...x}}catch(e){}}
function shuffle(a){a=a.slice();for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function heroPath(action){return `assets/characters/${state.character}_${action}.webp`}
function bossPath(n,action){return `assets/bosses/boss${n+1}_${action}.webp`}
function renderMap(){const p=state.completed.filter(Boolean).length*25;$("mapProgress").textContent=p+"%";$("mapCoins").textContent=state.coins;$("mapShards").textContent=state.shards;const box=$("levelCards");box.innerHTML="";LEVELS.forEach((l,i)=>{const b=document.createElement("button");b.className="levelCard"+(i>state.unlocked?" locked":"")+(state.completed[i]?" complete":"");b.innerHTML=`<img src="assets/backgrounds/${l.bg}"><h3>${l.name}</h3><p>隨機 10 題｜${state.completed[i]?"已完成":"尚未完成"}</p>`;if(i<=state.unlocked)b.onclick=()=>startLevel(i);box.appendChild(b)})}
function startLevel(i){run={level:i,questions:shuffle(bank.filter(q=>LEVELS[i].cat.includes(q.category))).slice(0,10),index:0,correct:0,lives:4,hints:3,combo:0,maxCombo:0,bossHp:100,answered:false};$("battleBg").style.backgroundImage=`url('assets/backgrounds/${LEVELS[i].bg}')`;$("levelName").textContent=LEVELS[i].name;$("bossImg").src=bossPath(i,"idle");$("heroImg").src=heroPath("idle");updateHud();renderQuestion();show("battle")}
function updateHud(){const pct=Math.round(((run.level*10+run.index)/40)*100);$("repair").textContent=pct+"%";$("coins").textContent=state.coins;$("shards").textContent=state.shards;$("lives").textContent="❤".repeat(run.lives)+"♡".repeat(4-run.lives);$("hintCount").textContent=run.hints;$("bossHp").style.width=run.bossHp+"%";$("bossHpText").textContent=`${run.bossHp}/100`}
function renderQuestion(){if(run.index>=10)return finishLevel();run.answered=false;const q=run.questions[run.index];$("qCategory").textContent=q.category;$("qCount").textContent=`${run.index+1}/10`;$("qText").textContent=q.question;$("feedback").textContent="";$("feedback").className="feedback";$("next").classList.add("hidden");const box=$("options");box.innerHTML="";q.options.forEach((t,i)=>{const b=document.createElement("button");b.className="opt";b.innerHTML=`<b>${String.fromCharCode(65+i)}.</b> ${t}`;b.onclick=()=>answer(i,b);box.appendChild(b)});$("heroImg").src=heroPath("idle");$("bossImg").src=bossPath(run.level,"idle")}
function answer(i,btn){if(run.answered)return;run.answered=true;const q=run.questions[run.index];const opts=[...document.querySelectorAll(".opt")];opts.forEach(x=>x.disabled=true);opts[q.answerIndex].classList.add("correct");if(i===q.answerIndex){run.correct++;run.combo++;run.maxCombo=Math.max(run.maxCombo,run.combo);run.bossHp=Math.max(0,run.bossHp-15);state.coins+=q.reward?.gold||5;state.shards+=2;btn.classList.add("correct");$("feedback").textContent="答對了！"+q.explanation;$("feedback").className="feedback good";$("heroImg").src=heroPath("attack");$("bossImg").src=bossPath(run.level,"hurt")}else{run.combo=0;run.lives--;btn.classList.add("wrong");$("feedback").textContent=`答案是「${q.answer}」。${q.explanation}`;$("feedback").className="feedback bad";$("heroImg").src=heroPath("hurt")}
 updateHud();if(run.lives<=0){setTimeout(()=>finishLevel(true),650);return}$("next").textContent=run.index===9?"查看結果":"下一題";$("next").classList.remove("hidden")}
function finishLevel(forceFail=false){const pass=!forceFail&&run.correct>=7;const l=LEVELS[run.level];$("resultTitle").textContent=pass?"修復成功！":"挑戰失敗…";$("resultArt").src=bossPath(run.level,pass?"dead":"idle");$("rCorrect").textContent=`${run.correct}/10`;$("rRate").textContent=Math.round(run.correct*10)+"%";$("rCombo").textContent=run.maxCombo;$("resultMsg").textContent=pass?"時間線已恢復穩定，獲得本關獎勵！":"至少答對 7 題才能完成修復，重新挑戰吧！";$("nextLevel").classList.toggle("hidden",!pass||run.level===3);if(pass){state.totalCorrect+=run.correct;if(!state.completed[run.level]){state.coins+=l.reward.coin;state.shards+=l.reward.shard}state.completed[run.level]=true;state.unlocked=Math.max(state.unlocked,Math.min(3,run.level+1));save();$("heroImg").src=heroPath("win")}show("result")}
$("next").onclick=()=>{run.index++;updateHud();renderQuestion()};$("hint").onclick=()=>{if(run.hints<=0||run.answered)return;run.hints--;const q=run.questions[run.index];$("feedback").textContent="提示：留意「"+(q.hint||q.tags?.[0]||"課文重點")+"」的意思。";$("feedback").className="feedback good";updateHud()};
$("retry").onclick=()=>startLevel(run.level);$("toMap").onclick=()=>{renderMap();show("map")};$("nextLevel").onclick=()=>{if(run.level===3)return showVictory();startLevel(run.level+1)};
function showVictory(){state.completed[3]=true;save();$("finalCorrect").textContent=`${state.totalCorrect}/40`;$("finalCoins").textContent=state.coins;$("finalShards").textContent=state.shards;show("victory")}
$("pause").onclick=()=>{$("modalTitle").textContent="任務暫停";$("modalText").textContent="休息一下，再繼續修復時間。";$("modal").classList.remove("hidden")};$("modalPrimary").onclick=()=>$("modal").classList.add("hidden");$("modalSecondary").onclick=()=>{$("modal").classList.add("hidden");renderMap();show("map")};
$("newGame").onclick=()=>show("select");$("continueGame").onclick=()=>{renderMap();show("map")};$("backHome").onclick=()=>show("home");document.querySelectorAll(".charCard").forEach(b=>b.onclick=()=>{state.character=b.dataset.char;save();renderMap();show("map")});
$("resetGame").onclick=()=>{if(confirm("確定要重置章節進度嗎？金幣與碎片也會恢復初始值。")){localStorage.removeItem("timeRepairV1");state={character:state.character,unlocked:0,completed:[false,false,false,false],coins:120,shards:35,totalCorrect:0};renderMap()}};
$("again").onclick=()=>{state.unlocked=0;state.completed=[false,false,false,false];state.totalCorrect=0;save();startLevel(0)};$("victoryMap").onclick=()=>{renderMap();show("map")};
load();if(localStorage.getItem("timeRepairV1"))$("continueGame").classList.remove("hidden");
})();